version: '3.3'

services:
    web:
        build: ./web
        ports: 
            - "5050:5050"
        volumes:
            - ./web/:/home/web/
            - ./files:/home/files/

        env_file:
            - dev.env